services:
  ros-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: dual-teleop-viz-noetic:latest
    container_name: dual-teleop-viz-ros
    volumes:
      - ../assets:/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    stdin_open: true
    tty: true
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    network_mode: host
    privileged: true
    command: /bin/bash
